### PR TITLE
Add carepeater

### PR DESCRIPTION
**Pull request by thomascobb**

### CODE REVIEW

**Review by willrogers — APPROVED** [review]
If this works then I think it is a useful addition.

**Comment by thomascobb** [comment]
@mdavidsaver two things:
- Should this belong in aioca or epicscorelibs?
- Is the wording in the docs and docstring I added correct?

**Comment by mdavidsaver** [comment]
> * Should this belong in aioca or epicscorelibs?

It could.  I don't have a strong opinion.

A better question is if libca should itself automatically fall back to an in-process repeater if the `caRepeater` executable can't be exec'd?

> * Is the wording in the docs and docstring I added correct?

Looks fine.

**Comment by thomascobb** [comment]
> A better question is if libca should itself automatically fall back to an in-process repeater if the `caRepeater` executable can't be exec'd?

That would be a lot better... Can we make that happen?

**Comment by willrogers** [comment]
Let's merge this into aioca as it allows you to get rid of a slight annoyance.

I think it belongs in epicscorelibs (it's not specific to aioca), but handling it in libca would seem like a good idea if it is possible.

**Comment by thomascobb** [comment]
I'm not sure if this goes away with a later release of epics-base:
https://github.com/epics-base/epics-base/pull/158

@mdavidsaver are the changes released in epicscorelibs and what do we need to do to enable the new behaviour?

**Comment by mdavidsaver** [comment]
The repeater fallback change is in [epicscorelibs>=7.0.5.99.1.0a2](https://pypi.org/project/epicscorelibs/7.0.5.99.1.0a2/).

**Comment by thomascobb** [comment]
Seems to have fixed it, so we don't need this now

**Pull request closed without merging**
